### Pandas DataFrame and Series

Series and DataFrame are the two foundational data structures of the Pandas library. A `Series` represents a single, one-dimensional column of data, while a `DataFrame` is a two-dimensional spreadsheet-like table composed of multiple grouped Series

In [18]:
import pandas as pd

In [19]:
## Series
# Series in one dimensional array like object that can hold any type of data.
data = [1,2,3,5,4]

ser = pd.Series(data)

print(ser)
print(type(ser))

0    1
1    2
2    3
3    5
4    4
dtype: int64
<class 'pandas.Series'>

In [20]:
# Series from dictionary
data = {'a':1, 'b':2, 'c':3, 'd':4}
dict_series = pd.Series(data)
print(dict_series)

a    1
b    2
c    3
d    4
dtype: int64

In [21]:
data = [1,2,3,4]
index = ['a', 'b', 'c', 'd']

series = pd.Series(data=data,
                   index=index)
series

a    1
b    2
c    3
d    4
dtype: int64

In [22]:
## DataFrame
# dataframe from dictioanry of list

data={
    'Name': ['Alex', 'Bob', 'Chalres'],
    'Age': [24, 25, 24],
    'City': ['Paris', 'Geneva', 'Toronto']
}

df = pd.DataFrame(data)

print(df)
print(type(df))

      Name  Age     City
0     Alex   24    Paris
1      Bob   25   Geneva
2  Chalres   24  Toronto
<class 'pandas.DataFrame'>

In [23]:
import numpy as np
np.array(df)  # converting DataFrame to an array

array([['Alex', 24, 'Paris'],
       ['Bob', 25, 'Geneva'],
       ['Chalres', 24, 'Toronto']], dtype=object)

In [24]:
# create DataFrame from list of dictionary
data = [
    {"Name": "Alex", "Age": 24, 'City': 'Paris'},
    {"Name": "Bob", "Age": 26, 'City': 'Geneva'},
    {"Name": "Charles", "Age": 24, 'City': 'Toronto'},
    {"Name": "Dia", "Age": 25, 'City': 'Auckland'}      
]

df = pd.DataFrame(data)

print(df)
print(type(df))

      Name  Age      City
0     Alex   24     Paris
1      Bob   26    Geneva
2  Charles   24   Toronto
3      Dia   25  Auckland
<class 'pandas.DataFrame'>

In [25]:
# reading data from csv file
df = pd.read_csv('sales_data.csv')

df.head()  # seeing first five records

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 5327: invalid start byte

In [26]:
df = pd.read_csv('sales_data.csv', encoding_errors='ignore')

df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [28]:
### last five recoreds
df.tail()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   str
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   str
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   str
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: float64(2), int64(7), str(16)
memory usage: 551.5 KB

In [29]:
# create DataFrame from list of dictionary
data = [
    {"Name": "Alex", "Age": 24, 'City': 'Paris'},
    {"Name": "Bob", "Age": 26, 'City': 'Geneva'},
    {"Name": "Charles", "Age": 24, 'City': 'Toronto'},
    {"Name": "Dia", "Age": 25, 'City': 'Auckland'}      
]

df = pd.DataFrame(data)

print(df)
print(type(df))

      Name  Age      City
0     Alex   24     Paris
1      Bob   26    Geneva
2  Charles   24   Toronto
3      Dia   25  Auckland
<class 'pandas.DataFrame'>

In [30]:
df['Name']  # accessing individual columns

0       Alex
1        Bob
2    Charles
3        Dia
Name: Name, dtype: str

In [32]:
print(type(df['Name']))  # cuz DataFrame is the collections of indivisual Series

<class 'pandas.Series'>

In [34]:
df.loc[0]  ## accessing the rows

Name     Alex
Age        24
City    Paris
Name: 0, dtype: object

In [35]:
df.iloc[0]

Name     Alex
Age        24
City    Paris
Name: 0, dtype: object

In [38]:
df.loc[0:1]

   Name  Age    City
0  Alex   24   Paris
1   Bob   26  Geneva

In [39]:
df.iloc[0:1]

   Name  Age   City
0  Alex   24  Paris

🔑 **Note**: Both loc and iloc can be used to acces the data, where loc is used to access the data with custom index, iloc is used for numerical/integer index.

**`loc` is inclusive of upper bound, while `iloc` is not**.

In [41]:
# Accessing a specifid elemnt
df

      Name  Age      City
0     Alex   24     Paris
1      Bob   26    Geneva
2  Charles   24   Toronto
3      Dia   25  Auckland

In [43]:
df.at[1, 'Age']

np.int64(26)

In [44]:
df.at[1, 'Name']

'Bob'

In [46]:
# accessing a soecified element with `iat`
df.iat[1, 0]

'Bob'